WIP: Upgrade to Python 3.11
async-worker/async-worker pull request #27
Opened 2023-02-17 18:48 UTC by timotta

2023-02-17 19:44 UTC, leotok commented on tests/signals/handlers/test_rabbitmq.py
>          # asynctest.MagicMock(
@timotta O que acha de remover esse cometário ou então adaptá-lo pra não usar o `asynctest`?

2023-02-17 19:52 UTC, leotok commented on tests/rabbitmq/test_rabbitmq_consumer.py
> +            queue_mock = Mock(
@timotta Nesse `queue_mock` está sendo usada a classe `Mock`, mas antes era `CoroutineMock` e na linha 667 quando é criado outro `queue_mock é usada a classe `AsyncMock`. Está certo ou era para ser o `AsyncMock` aqui tb?

2023-02-17 19:53 UTC, leotok commented on tests/rabbitmq/test_rabbitmq_consumer.py
> +            queue_mock = Mock(
Mesma dúvida na linha 691 e 713

2023-02-17 20:05 UTC, timotta commented on tests/signals/handlers/test_rabbitmq.py
>          # asynctest.MagicMock(
@leotok eu tentei mexer o minimo possivel (sem remover os comentarios ja existentes) mas acho que seria uma boa pratica se os owners @daltonmatos e @diogommartins acharem por bem eu dou uma limpa também.

2023-02-17 20:07 UTC, timotta commented on tests/rabbitmq/test_rabbitmq_consumer.py
> +            queue_mock = Mock(
@leotok estava errado antes queue_mock é apenas um objeto (e o CoroutineMock ao contrário do MagicMock não propaga a magica). Não causava dano usar CoroutineMock, mas também não trazia beneficio e causava confusão (vc esperaria em algum momento um await queue_mock())

2023-02-27 02:54 UTC, diogommartins requested changes

2023-02-27 02:54 UTC, diogommartins commented on asyncworker/time.py
> +        self._sleep = asyncio.sleep
Não precisamos guardar uma referência pro `asyncio.sleep` no objeto. Basta fazer o `patch` direto no `asyncio.sleep`, @timotta:

```patch
Index: tests/test_time.py

<+>UTF-8
===================================================================
diff --git a/tests/test_time.py b/tests/test_time.py
--- a/tests/test_time.py	(revision 1f7bf2bbe7a0175493a1fcd90ca5419c39a55af2)
+++ b/tests/test_time.py	(date 1677466264709)
@@ -55,10 +55,11 @@
                 event.clear.assert_not_called()
                 await clock.stop()
 
-            clock._sleep = AsyncMock(side_effect=tick_check)
-
-            clock._running = True
-            await self.loop.create_task(clock._run())
-            event.clear.assert_called_once()
+            with patch(
+                "asyncworker.time.asyncio.sleep", AsyncMock(side_effect=tick_check)
+            ) as sleep:
+                clock._running = True
+                await self.loop.create_task(clock._run())
+                event.clear.assert_called_once()
 
-            clock._sleep.assert_awaited_once_with(2)
+                sleep.assert_awaited_once_with(2)
Index: asyncworker/time.py

<+>UTF-8
===================================================================
diff --git a/asyncworker/time.py b/asyncworker/time.py
--- a/asyncworker/time.py	(revision 1f7bf2bbe7a0175493a1fcd90ca5419c39a55af2)
+++ b/asyncworker/time.py	(date 1677466160996)
@@ -31,7 +31,6 @@
         self._tick_event = asyncio.Event()
         self._running: Optional[bool] = None
         self._main_task: Optional[asyncio.Future] = None
-        self._sleep = asyncio.sleep
 
     def __aiter__(self) -> AsyncIterator:
         if self._running is not None:
@@ -55,7 +54,7 @@
     async def _run(self) -> None:
         while self._running:
             self._tick_event.set()
-            await self._sleep(self.seconds)
+            await asyncio.sleep(self.seconds)
             self._tick_event.clear()
 
     async def stop(self) -> None:

```

2023-02-27 02:59 UTC, diogommartins commented on .github/workflows/pull-request.yaml
> +        python: [3.9, 3.10, 3.11]
```suggestion
        python: ["3.9", "3.10", "3.11"]
```

2023-03-01 15:48 UTC, diogommartins commented on .github/workflows/main.yaml
> +        python: [3.9, 3.10, 3.11]
```suggestion
        python: ['3.9', '3.10', '3.11']
```

2023-03-01 15:52 UTC, diogommartins commented on .github/workflows/main.yaml
> +        python: ['3.9', '3.10', '3.11']
Aqui removemos o `3.x`. Não é uma boa voltar com ele pra que a gente eventualmente rode (e saiba se algo quebrou) no `3.12`, `3.13`, ... ?

2023-03-01 16:05 UTC, diogommartins commented
## 3.9.16
```
Traceback (most recent call last):
[20](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:21)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/py.test", line 5, in <module>
[21](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:22)
    from pytest import console_main
[22](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:23)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
[23](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:24)
    from _pytest._code import ExceptionInfo
[24](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:25)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
[25](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:26)
    from .code import Code
[26](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:27)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/_pytest/_code/code.py", line 60, in <module>
[27](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:28)
    from exceptiongroup import BaseExceptionGroup
[28](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:29)
ModuleNotFoundError: No module named 'exceptiongroup'
```
https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808

## 3.10.10

```
Traceback (most recent call last):
[20](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:21)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/bin/py.test", line 5, in <module>
[21](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:22)
    from pytest import console_main
[22](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:23)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/pytest/__init__.py", line 5, in <module>
[23](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:24)
    from _pytest._code import ExceptionInfo
[24](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:25)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/_code/__init__.py", line 2, in <module>
[25](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:26)
    from .code import Code
[26](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:27)
  File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 60, in <module>
[27](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:28)
    from exceptiongroup import BaseExceptionGroup
[28](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:29)
ModuleNotFoundError: No module named 'exceptiongroup'
[29](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:30)
Error: Process completed with exit code 1.
```
https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022

Você teve algum problema para executar os testes localmente nessas versões, @timotta ? Vi que o 3.11 passou pelos testes de boa, mas [quebrou no upload de coverage](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636228)

2023-03-01 17:11 UTC, diogommartins commented
> ## 3.9.16
> ```
> Traceback (most recent call last):
> [20](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:21)
>   File "/opt/hostedtoolcache/Python/3.9.16/x64/bin/py.test", line 5, in <module>
> [21](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:22)
>     from pytest import console_main
> [22](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:23)
>   File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/pytest/__init__.py", line 5, in <module>
> [23](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:24)
>     from _pytest._code import ExceptionInfo
> [24](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:25)
>   File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/_pytest/_code/__init__.py", line 2, in <module>
> [25](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:26)
>     from .code import Code
> [26](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:27)
>   File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/_pytest/_code/code.py", line 60, in <module>
> [27](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:28)
>     from exceptiongroup import BaseExceptionGroup
> [28](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808#step:8:29)
> ModuleNotFoundError: No module named 'exceptiongroup'
> ```
> 
> https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507635808
> 
> ## 3.10.10
> ```
> Traceback (most recent call last):
> [20](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:21)
>   File "/opt/hostedtoolcache/Python/3.10.10/x64/bin/py.test", line 5, in <module>
> [21](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:22)
>     from pytest import console_main
> [22](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:23)
>   File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/pytest/__init__.py", line 5, in <module>
> [23](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:24)
>     from _pytest._code import ExceptionInfo
> [24](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:25)
>   File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/_code/__init__.py", line 2, in <module>
> [25](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:26)
>     from .code import Code
> [26](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:27)
>   File "/opt/hostedtoolcache/Python/3.10.10/x64/lib/python3.10/site-packages/_pytest/_code/code.py", line 60, in <module>
> [27](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:28)
>     from exceptiongroup import BaseExceptionGroup
> [28](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:29)
> ModuleNotFoundError: No module named 'exceptiongroup'
> [29](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022#step:8:30)
> Error: Process completed with exit code 1.
> ```
> 
> https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636022
> 
> Você teve algum problema para executar os testes localmente nessas versões, @timotta ? Vi que o 3.11 passou pelos testes de boa, mas [quebrou no upload de coverage](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636228)
> 
> ```
> Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
> ```

2023-03-01 17:11 UTC, diogommartins commented
Existe um secret CC_TEST_REPORTER_ID no projeto. Talvez só esteja faltando definir uma env com esse secret?

2023-03-01 17:16 UTC, diogommartins commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
Env sendo definida aqui

2023-03-01 17:21 UTC, diogommartins commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
@daltonmatos pedi uma permissão na org `async-worker` relacionada ao codecov. Deve ter chegado alguma coisa no seu e-mail. Pode autorizar ?

2023-03-02 02:24 UTC, daltonmatos commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
Aprovei. Estamos adicionando codecov no repo do async-worker? A ideia seria trocar o codeclimate por ele?

2023-03-02 02:24 UTC, daltonmatos commented
Pessoal, 

estou acompanhando um pouco de longe esse PR mas desde já agradeço muito o esforço e assim que tiver mais tempo vou olhar com mais detalhe e responder/opinar as dúvidas. 

Valeu!!

2023-03-04 13:38 UTC, timotta commented on asyncworker/time.py
> +        self._sleep = asyncio.sleep
@diogommartins vc tem razão, é mania de ex-javeiro de preferir fazer as coisas por injeção de dependência. Farei aqui a modificação

2023-03-04 13:45 UTC, timotta commented on .github/workflows/main.yaml
> +        python: ['3.9', '3.10', '3.11']
Faz sentido! Na boa, acho que tirei o 3.x por distração, não foi consciente.

2023-03-04 13:53 UTC, timotta commented on .github/workflows/main.yaml
> +        python: ['3.9', '3.10', '3.11']
> 
> Você teve algum problema para executar os testes localmente nessas versões, @timotta ? Vi que o 3.11 passou pelos testes de boa, mas [quebrou no upload de coverage](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636228)
> 
> ```
> Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
> ```

Localmente testei apenas na versão 3.11. Vou testar agora nessas versões e ajustar para que fiquem OK.

2023-03-04 13:53 UTC, timotta commented
> 
> Você teve algum problema para executar os testes localmente nessas versões, @timotta ? Vi que o 3.11 passou pelos testes de boa, mas [quebrou no upload de coverage](https://github.com/async-worker/async-worker/actions/runs/4305340383/jobs/7507636228)
> 
> ```
> Error: you must supply a CC_TEST_REPORTER_ID ENV variable or pass it via the -r flag
> ```

Localmente testei apenas na versão 3.11. Vou testar agora nessas versões e ajustar para que fiquem OK.

2023-03-04 14:16 UTC, timotta commented
> > ModuleNotFoundError: No module named 'exceptiongroup'

Parece que esse erro estava presente no pytest 7.2.1. Atualizado para 7.2.2 o problema resolveu no python 3.9, 3.10 e 3.11 se manteve.

2023-03-05 19:34 UTC, diogommartins commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
Tem algo esquisito na relação entre o [codeclimate e PRs de forks](https://github.com/codeclimate/test-reporter/issues/452). Me parece que ele não tá passando env nesse contexto. Com as ultimas alterações do @timotta, [só a step do codeclimate continua quebrando](https://github.com/async-worker/async-worker/actions/runs/4331343146/jobs/7573751123) :/

2023-03-05 21:14 UTC, timotta commented
@daltonmatos ainda estamos com erro na execução do upload de cobertura pela falta da env `CC_TEST_REPORTER_ID`. Olhando o log da action da pra ver que a env realmente está vazia. Me pergunto se isso não está acontecendo por alguma proteção de segurança (por ser um PR via fork, faz sentido ter uma proteção para que quem faz o PR não tenha como obter as secrets)

2023-03-05 21:16 UTC, timotta commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
Acho que faz sentido a secret não ficar exposta nesse PR pois é um PR vindo de um fork. Se essa secret ficasse exposta a qualquer PR via fork, seria facil obter ela adicionando actions para fazer upload dela pra um server do dono do fork.

2023-03-06 02:32 UTC, diogommartins commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
Exato. Por padrão, secrets não são compartilhados com forks, [apesar dessa opção existir](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/). Se não queremos compartilhar, não bastaria alterar a condição para não rodar em forks, algo como ` if: env.CC_TEST_REPORTER_ID && matrix.python_version == '3.11'`  @timotta ?

2023-03-07 14:44 UTC, diogommartins commented on .github/workflows/pull-request.yaml
> +        if: ${{matrix.python == '3.11'}}
```suggestion
        if: env.CC_TEST_REPORTER_ID && matrix.python_version == '3.11'
```

2023-03-10 00:14 UTC, timotta commented on .github/workflows/pull-request.yaml
>            CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
@diogommartins comitei a sugestão do @daltonmatos que é exata a essa que vc sugeriu aí

2023-03-11 19:13 UTC, diogommartins approved these changes

2023-03-27 21:56 UTC, merged

2023-04-06 00:22 UTC, daltonmatos commented
Acho podemos sim @timotta. O que fizemos aqui, apesar de ser apenas update de compatibilidade com python, melhor gerarmos uma [release breaking](https://async-worker.github.io/async-worker/versions.html#atualizacao-de-dependencias).

Vou publicar o draft da versão `0.20.0`. 

Lembro do @diogommartins ter comentado sobre um problema nos workflows que apesar do python escolhido ser uma versão X o workflow estava ainda rodando com uma versão Y. Conseguimos descobrir o que estava causando isso?

2023-04-08 18:16 UTC, daltonmatos commented
@timotta 

PR para podermos fechar a release `0.20.0`. https://github.com/async-worker/async-worker/pull/30

2023-04-18 19:50 UTC, daltonmatos commented
Feito. https://pypi.org/project/async-worker/0.20.0/